version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: pingerbot
      POSTGRES_PASSWORD: password
      POSTGRES_DB: pingerbotdb

  bot:
    image: pingerbot:latest
    restart: always