[tool.poetry]
name = "PingerBot"
version = "0.2.0.dev"
description = "Почти доделанная альтернатива RuMineBot."
authors = ["PerchunPak <perchunpak@gmail.com>"]
license = "Apache License 2.0"

[tool.poetry.dependencies]
python = "^3.7"

"discord.py" = "^1.7"
asyncpg = "^0.25"
matplotlib = "^3.5"
mcstatus = "^9.0"

[tool.poetry.dev-dependencies]
pytest = "^7.1"
pytest-cov = "^3.0"
pytest-asyncio = "^0.18"
dpytest = "^0.5"
flake8 = "^4"
pylint = "^2.13"
black = "^22.3"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
