[tool.poetry]
name = "PingerBot"
version = "0.1.0.dev"
description = "Почти доделанная альтернатива RuMineBot."
authors = ["PerchunPak <perchunpak@gmail.com>"]
license = "Apache License 2.0"

[tool.poetry.dependencies]
python = "^3.7"

"discord.py" = "^1.7"
asyncpg = "^0.25"
matplotlib = "^3.5"
mcstatus = "^9.0"

[tool.poetry.dev-dependencies]
black = "^22"
flake8 = "^4"

pytest = "^7.1"
pytest-asyncio = "^0.18"
pytest-cov = "^3.0"
dpytest = "^0.5"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
