[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"


[tool.poetry]
name = "pinger-bot"
description = "Простой бот для отслеживания статуса и статистики своих MineCraft серверов."
version = "0.4.0.dev"
license = "AGPL3"

authors = ["Perchun Pak <perchunpak@gmail.com>"]

readme = "README.md"

repository = "https://github.com/PerchunPak/pinger-bot"

[tool.poetry.dependencies]
python = "^3.8,<3.11"

# Our dependecies
hikari = "~2.0.0-dev"
hikari-lightbulb = "~2.2"
APScheduler = "~3.9"

mcstatus = "~9.0"
SQLAlchemy = {version = "~1.4", extras = ["asyncio"]}
alembic = "~1.8"
dnspython = "~2.2"
omegaconf = "~2.2"
matplotlib = "~3.5"
requests = "*"

Babel = "~2.10"

structlog = "21.5.0"
### For colors in structlog ###
### Only needed for Windows ###
colorama = { version = "*", markers="platform_system == 'Windows'" }
# Speedup for async, only for unix-like systems
uvloop = { version = "*", markers="os_name != 'nt'" }

# Docs
sphinx                   = { version = "~5.0",  optional = true }
sphinx-autodoc-typehints = { version = "~1.18", optional = true }
sphinx-autoapi           = { version = "~1.8",  optional = true }
sphinx-intl              = { version = "~2.0",  optional = true }
furo                     = { version = "*",     optional = true }
m2r2                     = { version = "~0.3",  optional = true }
tomli                    = { version = "~2.0",  optional = true }
packaging                = { version = "21.3",  optional = true }
sphobjinv                = { version = "~2.2",  optional = true }

# SQLAlchemy
aiomysql  = { version = "*",               optional = true }
aiosqlite = { version = "*",               optional = true }
asyncpg   = { version = "*",               optional = true }

[tool.poetry.dev-dependencies]
black = "~22"
isort = "~5.10"
pycln = "~1.3"
doc8 = "~0.11"
pre-commit = "~2.19"
mypy = "0.961"
flake8 = "~4"
flake8-docstrings = "~1"
pydocstyle = ">=4.0.0"

safety = "~1.10"

pytest = "~7.1"
pytest-cov = "~3.0"
pytest-mock = "~3.7"
pytest-testmon = "~1.3"
pytest-randomly = "~3.12"

SQLAlchemy = {version = "~1.4", extras = ["mypy"]}

[tool.poetry.extras]
docs = ["sphinx", "sphinx-autodoc-typehints", "sphinx-autoapi", "sphinx-intl","furo", "m2r2", "tomli", "packaging", "sphobjinv"]

# SQLAlchemy
mysql = ["aiomysql"]
sqlite = ["aiosqlite"]
postgresql = ["asyncpg"]

[tool.black]
line-length = 120
target-version = ['py310']
