name: Black Formatter - rewrite

on:
  schedule:
    - cron: '0 3 * * 1'

jobs:
  apply-black-style:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ github.job }}
    - name: Install dependencies
      run: |
        pip install -U pip
        pip install -Ur requirements.txt -r tests_requirements.txt
    - name: Apply Black code style
      run: |
        black . -l 127
    - name: Commit files
      continue-on-error: true
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git commit -m "Aplied Black code style" -a
    - name: Push changes
      continue-on-error: true
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}
