# Автоматические тесты через GitHub Actions

name: Run Tests in rewrite

on:
  push:
    branches:
    - rewrite

env:
  PINGERBOT_POSTGRES: postgres://pingerbot:password@localhost:5432/pingerbotdb

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ github.job }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -Ur tests_requirements.txt
    - name: Lint with flake8
      run: |
        # крашит билд если есть ошибки синтаксиса или не обьявленные переменные
        flake8 . --exclude .*,__*__,venv --count --select=E9,F63,F7,F82 --show-source
        # exit-zero переводит все ошибки в предупреждения. Редактор GitHub 127 символов в ширину
        flake8 . --exclude .*,__*__,venv --count --exit-zero --max-complexity=10 --max-line-length=127 --ignore=E70
    - name: Lint with PyLint
      run: |
        # ужасный линтер, тупой и умный одновременно
        #
        # указываем все файлы корневой директории
        pylint *.py --rcfile=.pylint --exit-zero
        # смотрим на файлы в папке src и src/commands
        pylint src --rcfile=.pylint --exit-zero
        # потом смотрим в папке tests, из за особенностей pytest нужно в disable добавить W0621 и W0613
        pylint tests --rcfile=tests/.pylint --exit-zero
  test:
    needs: lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9, '3.10']
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: pingerbot
          POSTGRES_PASSWORD: password
          POSTGRES_DB: pingerbotdb
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ github.job }}
    - name: Install dependencies
      run: |
        pip install -U pip
        pip install -Ur requirements.txt -r tests_requirements.txt
    - name: Test with pytest
      run: pytest
      env:
        PGHOST: localhost
        PGPORT: 5432
        PGUSER: pingerbot
        PGPASSWORD: password
        PGDATABASE: pingerbotdb
    - name: Upload HTML report by Coverage (only on Python 3.9)
      if: ${{ matrix.python-version == 3.9 }}
      uses: actions/upload-artifact@v2
      with:
        name: HTML report by Coverage
        path: ./htmlcov
  deploy:
    needs: test
    if: |
        needs.test.result == 'success' && 
        github.event_name != 'pull_request' && 
        github.actor == 'PerchunPak'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: FTP Deploy
      continue-on-error: true
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp-server: ${{ secrets.ftp_server }}
        ftp-username: ${{ secrets.ftp_username }}
        ftp-password: ${{ secrets.ftp_password }}
        git-ftp-args: --insecure
