# Автоматические тесты через GitHub Actions

name: Run Tests in newdb

on:
  push:
    branches:
    - newdb

env:
  PINGERBOT_POSTGRES: postgres://pingerbot:password@localhost:5432/pingerbotdb

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ github.job }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -Ur tests_requirements.txt
    - name: Lint with flake8
      run: |
        # крашит билд если есть ошибки синтаксиса или не обьявленные переменные
        flake8 . --exclude .*,__*__,venv --count --select=E9,F63,F7,F82 --show-source
        # exit-zero переводит все ошибки в предупреждения. Редактор GitHub 127 символов в ширину
        flake8 . --exclude .*,__*__,venv --count --exit-zero --max-complexity=10 --max-line-length=127 --ignore=E70,W503
    - name: Lint with PyLint
      run: |
        # ужасный линтер, тупой и умный одновременно
        #
        # указываем все файлы корневой директории
        pylint *.py --rcfile=.pylint --exit-zero
        # смотрим на файлы в папке src и src/commands
        pylint src --rcfile=.pylint --exit-zero
        # потом смотрим в папке tests, из за особенностей pytest нужно в disable добавить W0621, W0613 и др.
        pylint tests --rcfile=tests/.pylint --exit-zero
    # Показывает изменения которые бы ввел black
    # Раз в месяц, они сами применяются
    - name: Use black Auto-formatter
      run: black . -l 127 --diff
