# Автоматические тесты через GitHub Actions

name: Run Tests in rewrite

on:
  push:
    branches:
    - rewrite

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ${{ env.pythonLocation }}
        key: ${{ env.pythonLocation }}-${{ github.job }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -U flake8==4.0.1
    - name: Lint with flake8
      run: |
        # крашит билд если есть ошибки синтаксиса или не обьявленные переменные
        flake8 . --exclude .*,__*__,venv --count --select=E9,F63,F7,F82 --show-source
        # exit-zero переводит все ошибки в предупреждения. Редактор GitHub 127 символов в ширину
        flake8 . --exclude .*,__*__,venv --count --exit-zero --max-complexity=10 --max-line-length=127 --ignore=E70
